### ISSUE TITLE
ASAN: malloc vs delete mismatch

### ISSUE THREAD

**Issue by abique** [jackaudio/jack2#237]
Hi,

I got this issue recently

==27525==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete) on 0x60300004f180
    #0 0x7ffff6f00520 in operator delete(void*) /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_new_delete.cc:92
    #1 0x7ffff5ebbd88  (/usr/lib/libjack.so.0+0x12d88)
    #2 0x7ffff5eb68e9 in jack_port_register (/usr/lib/libjack.so.0+0xd8e9)

Good luck!

**Comment by sletz** [comment]
Without any more precise log it is just unusable...

**Comment by abique** [comment]
I believe you could wrap the delete with std::unique_ptr<>? Then you can easily find the mismatch with what is left?
Or use some static analysis?

**Comment by abique** [comment]
And also the mismatch happens in jack_port_register so I believe that there are not so many things going on there...

**Comment by milasudril** [comment]
Do you use overrides for operator new? If so C++14 adds some more entry points to define. See https://github.com/milasudril/snowflake-toolkit/commit/1f4ce0a7bc16e88606a9d2ae07656f27a9a7199b
