### ISSUE TITLE
Jack becomes unresponsive with some clients / high cpu usage

### ISSUE THREAD

**Issue by kjyv** [jackaudio/jack2#297]
I'm encountering an issue where a client connected to jackd (e.g. mod-host) works fine for a couple of seconds up to minutes (audio from one plugin, midi input) but then locks up. All client processes stop using cpu, jack is still running and is using a few percent cpu as normal but is not accepting new clients anymore (e.g. jack_lsp). No audio is output anymore. The moment when the plugin stops working, strace \`pidof mod-host\` shows
```
(...)
[pid 11092] futex(0x76fb9000, FUTEX_WAIT, 0, {tv_sec=2147, tv_nsec=483647000} <unfinished ...>
[pid 11099] futex(0x76f81000, FUTEX_WAIT, 0, {tv_sec=2147, tv_nsec=483647000} <unfinished ...>
[pid 11091] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 11091] futex(0x3c3e00, FUTEX_WAIT_PRIVATE, 0, {tv_sec=1, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
[pid 11091] futex(0x3c3e00, FUTEX_WAIT_PRIVATE, 0, {tv_sec=1, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
[pid 11091] futex(0x3c3e00, FUTEX_WAIT_PRIVATE, 0, {tv_sec=1, tv_nsec=0}) = -1 ETIMEDOUT (Connection timed out)
(...)
```
and the client is stuck.
Doing the same with another jack client (amsynth) results in the same behavior.

Output from an strace on jackd first repeats the following as long as it is working.
```
[pid 17479] futex(0x76f2e000, FUTEX_WAKE, 1) = 1
[pid 17479] poll([{fd=6, events=POLLOUT|POLLERR|POLLNVAL}, {fd=7, events=POLLIN|POLLERR|POLLNVAL}], 2, 8706) = 1 ([{fd=6, revents=POLLOUT}])
[pid 17479] poll([{fd=7, events=POLLIN|POLLERR|POLLNVAL}], 1, 8706) = 1 ([{fd=7, revents=POLLIN}])
[pid 17479] ioctl(7, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82ca8) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(7, SNDRV_PCM_IOCTL_STATUS_EXT, 0x713afcd8) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_DROP, 0x2) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_PREPARE, 0x1db61d4) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
```

Then once it gets stuck the output gives (single time):
```
[pid 17479] mmap2(NULL, 2097152, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x70f00000
[pid 17479] munmap(0x71000000, 1048576) = 0
[pid 17479] mprotect(0x70f00000, 135168, PROT_READ|PROT_WRITE) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_START, 0x1d82a28) = 0
```

and then repeated blocks of
```
[pid 17479] write(8, " \0\0\0", 4)      = 4
[pid 17480] <... poll resumed> )        = 1 ([{fd=10, revents=POLLIN}])
[pid 17479] write(8, "\f\0\0\0", 4 <unfinished ...>
[pid 17480] read(10,  <unfinished ...>
[pid 17479] <... write resumed> )       = 4
[pid 17480] <... read resumed> " \0\0\0", 4) = 4
[pid 17479] write(8, "\377\377\377\377", 4 <unfinished ...>
[pid 17480] read(10,  <unfinished ...>
[pid 17479] <... write resumed> )       = 4
[pid 17480] <... read resumed> "\f\0\0\0", 4) = 4
[pid 17479] write(8, "\3\0\0\0", 4 <unfinished ...>
[pid 17480] read(10,  <unfinished ...>
[pid 17479] <... write resumed> )       = 4
[pid 17480] <... read resumed> "\377\377\377\377", 4) = 4
[pid 17479] write(8, "\0\0\0\0", 4 <unfinished ...>
[pid 17480] read(10,  <unfinished ...>
[pid 17479] <... write resumed> )       = 4
[pid 17480] <... read resumed> "\3\0\0\0", 4) = 4
[pid 17479] poll([{fd=6, events=POLLOUT|POLLERR|POLLNVAL}, {fd=7, events=POLLIN|POLLERR|POLLNVAL}], 2, 8706 <unfinished ...>
[pid 17480] read(10, "\0\0\0\0", 4)     = 4
[pid 17480] poll([{fd=5, events=POLLIN|POLLERR}, {fd=10, events=POLLIN|POLLPRI|POLLERR|POLLHUP|POLLNVAL}, {fd=11, events=POLLIN|POLLPRI|POLLERR|POLLHUP|POLLNVAL}
], 3, 10000 <unfinished ...>
[pid 17479] <... poll resumed> )        = 1 ([{fd=6, revents=POLLOUT}])
[pid 17479] poll([{fd=7, events=POLLIN|POLLERR|POLLNVAL}], 1, 8706) = 1 ([{fd=7, revents=POLLIN}])
[pid 17479] ioctl(7, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82ca8) = 0
[pid 17479] ioctl(7, SNDRV_PCM_IOCTL_XRUN, 0x1d82cb4) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(7, SNDRV_PCM_IOCTL_STATUS_EXT, 0x713afcd8) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_DROP, 0x2) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_PREPARE, 0x1db61d4) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_SYNC_PTR, 0x1d82a28) = 0
[pid 17479] ioctl(6, SNDRV_PCM_IOCTL_START, 0x1d82a28) = 0
```

Gdb bt after sound stopped:
$ gdb -batch -ex bt -p `pidof jackd`
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
do_sigwait (set=<optimized out>, set@entry=0x76ee71a0 <sigmask>, sig=sig@entry=0x7ee0bc70) at ../sysdeps/unix/sysv/linux/sigwait.c:64
64      ../sysdeps/unix/sysv/linux/sigwait.c: No such file or directory.
#0  do_sigwait (set=<optimized out>, set@entry=0x76ee71a0 <sigmask>, sig=sig@entry=0x7ee0bc70) at ../sysdeps/unix/sysv/linux/sigwait.c:64
#1  0x76df6784 in __sigwait (set=0x76ee71a0 <sigmask>, sig=0x7ee0bc70) at ../sysdeps/unix/sysv/linux/sigwait.c:96
#2  0x76ea1d70 in jackctl_wait_signals () from /usr/lib/libjackserver.so.0
#3  0x000129f0 in ?? ()
#4  0x76a4b678 in __libc_start_main (main=0x7ee0c0e4, argc=1991704576, argv=0x76a4b678 <__libc_start_main+276>, init=<optimized out>, fini=0x1358c, rtld_fini=0x76f1c9b8 <_dl_fini>, stack_end=0x7ee0c0e4) at libc-start.c:291
#5  0x00011424 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

All of this is on a raspberry pi with a realtime kernel 4.9.52. The behavior is the same if the vanilla kernel from system packages (4.9.41, non RT) is used but it seems to take longer to occur. I also tested with an older jack version (from packages, 1.9.10+20150825git1ed50c92).
Also, please suggest any more ideas on debugging this.

**Comment by kjyv** [comment]
Oh, and I noticed I can't seem to reproduce this on raspbian jessie, with otherwise pretty much the same setup. I've tried with the same gcc version on stretch (4.9 vs 6.3) but this doesn't help.

**Comment by kjyv** [comment]
While trying jackd1 for comparison I've got the same behavior but more error messages that might lead to what jackd2 is doing.
While I'm not sure I understand the reasoning to kick out clients that have xruns (and also that behavior should be disabled with -Z), in any case this should leave jack in a usable state. However, any further connection attempts just get stuck as described before. It now looks to me like mod-host is not handling the error case properly?

The log show a few sections like the following that actually show an xrun:
```
load = 68.4625 max usecs: 4798.000, spare = 1006.000
load = 68.2251 max usecs: 3946.000, spare = 1858.000

**** alsa_pcm: xrun of at least 0.194 msecs

client event poll on 18 for mod-host starts at 296812848
back from client event poll after 78 usecs
client event poll on 20 for effect_0 starts at 296812947
back from client event poll after 42 usecs
subgraph starting at mod-host timed out (subgraph_wait_fd=12, status = 0, state = Finished, pollret = 0 revents = 0x0)
bad status (255) from client effect_0 while handling a latency callback event
at 296824436 waiting on 12 for 6237 usecs, status = 1 sig = 296818180 awa = 296818229 fin = 296818255 dur=75
checking client alsa_pcm: awake at 0 finished at 0
checking client alsa_midi: awake at 0 finished at 0
checking client mod-host: awake at 296818229 finished at 296818255
checking client effect_0: awake at 296818277 finished at 0
client effect_0 has timed out
waking server thread
server thread back from poll
bad status (255) from client effect_0 while handling a latency callback event
trying to lock graph to remove 1 problems
client effect_0 already marked with error = 1

(...)
```
After a few of those it just repeats something like the following often without reporting runs until jack is not reactive anymore:

```
waking server thread
bad status (255) from client effect_0 while handling a latency callback event
server thread back from poll
trying to lock graph to remove 1 problems
we have problem clients (problems = 1
++ Removing failed clients ...
client alsa_pcm error status 0
client alsa_midi error status 0
client mod-host error status 0
client effect_0 error status 1
client failure: client effect_0 state = Finished errors = 1
++ jack_sort_graph
client event poll on 18 for mod-host starts at 296951034
back from client event poll after 162 usecs
client event poll on 18 for mod-host starts at 296951223
bad status (255) from client effect_0 while handling a latency callback event
bad status (255) from client effect_0 while handling a graph reordered event
back from client event poll after 50 usecs
++ jack_rechain_graph():
+++ client is now effect_0 active ? 1
client effect_0: start_fd=7, execution_order=0.
+++ client is now mod-host active ? 1
client mod-host: in subgraph after effect_0, execution_order=1.
client event poll on 18 for mod-host starts at 296951403
back from client event poll after 107 usecs
client effect_0: wait_fd=12, execution_order=2 (last client).
-- jack_rechain_graph()
-- jack_sort_graph
-- Removing failed clients ...
after removing clients, problems = 0
start poll on 5 fd's
client effect_0 already marked with error = 1
```

**Comment by fps** [comment]
Is this using a USB audio device? All my experiments on varying versions of raspberry pi's up to model 3+ were unsuccessfull. The USB host controller on these things is just horrible.

USB audio and jack works just fine on the raspberry pi 4.. (USB audio device class 2.0 devices on the USB 3 port).

**Comment by kjyv** [comment]
I might have used USB back then, but I think it also happened with internal cards. Setting different buffer sizes maybe can help. I didn't have any of these issues in a long time, so this might have been a combination of kernel, compiler, hardware. Dunno :)

**Comment by CubeArmyForever** [comment]
hi
