### ISSUE TITLE
 Process org.jackaudio.service exited with status 1

### ISSUE THREAD

**Issue by bendavis78** [jackaudio/jack2#326]
I'm unable to use `jack2-dbus`:

```
$ jack_control start

Traceback (most recent call last):
  File "/usr/bin/jack_control", line 399, in <module>
    main()
  File "/usr/bin/jack_control", line 160, in main
    controller = bus.get_object(service_name, "/org/jackaudio/Controller")
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.jackaudio.service exited with status 1

```

**Comment by brynedwards** [comment]
I'm using `jack2-dbus` on Arch Linux and it logs to `~/.log/jack/jackdbus.log`. Do you have any logs there that might be useful?

**Comment by bendavis78** [comment]
Interesting. For whatever reason, I had a file in my home dir called `~/.log` (not a directory). Once I deleted that file and ran `mkdir -p ~/.log/jack`, The `jack_control start` command worked! I'm guessing the process was trying to create that directory and couldn't because it was already a file. Perhaps some better error reporting in the python process would help users debug this type of error in the future (although my use case was pretty obscure).
