### ISSUE TITLE
Meta-data delete all crashes the client

### ISSUE THREAD

**Issue by falkTX** [jackaudio/jack2#390]
```
$ gdb --args jack_property -D
...
Thread 1 "jack_property" received signal SIGSEGV, Segmentation fault.
__strncpy_ssse3 () at ../sysdeps/x86_64/multiarch/strcpy-ssse3.S:43
43      ../sysdeps/x86_64/multiarch/strcpy-ssse3.S: No such file or directory.
(gdb) bt
#0  __strncpy_ssse3 () at ../sysdeps/x86_64/multiarch/strcpy-ssse3.S:43
#1  0x00007ffff7b97301 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x00007ffff7b88dc1 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#3  0x00007ffff7bb9686 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00005555555551ea in ?? ()
#5  0x00007ffff77a9b97 in __libc_start_main (main=0x555555554de0, argc=2, argv=0x7fffffffdcd8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcc8) at ../csu/libc-start.c:310
#6  0x000055555555568a in ?? ()
```

**Comment by falkTX** [comment]
@rncbc maybe something you can take a look at?
I will try it myself soon anyway. this is a release blocker.
