### ISSUE TITLE
jack2-1.9.14 segfaults on raspbian 2019-07-10

### ISSUE THREAD

**Issue by hires** [jackaudio/jack2#533]
I'm building jack2 from source on raspbian and it builds and installs, and looks to be running fine. But as soon as a client connects jackd segfaults.  I only tested with njconnect as my application is not fully set up on the pi yet. The error seen by the client is: jack_client_open() failed, status = 0x21

Below is the backtrace from gdb. g++ -v reports: gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 

Any help would be greatly appreciated. :)

```
Thread 4 "jackd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x712233e0 (LWP 19972)]
strlen () at ../sysdeps/arm/armv6/strlen.S:26
26	../sysdeps/arm/armv6/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/arm/armv6/strlen.S:26
#1  0x76ad7de0 in _IO_vfprintf_internal (s=s@entry=0x71221a30, 
    format=format@entry=0x76f83e84 "JackEngine::ClientExternalOpen: uuid = %d, name = %s", ap=..., ap@entry=...)
    at vfprintf.c:1638
#2  0x76afb278 in _IO_vsnprintf (
    string=0x71221b5e "JackEngine::ClientExternalOpen: uuid = 1995980420, name = \364\033\"q\210\245\355vT\034\"q\374\033\"q\350\224\377v\264\210\375v\374\033\"q\330\372\377v\002", maxlen=<optimized out>, 
    format=0x76f83e84 "JackEngine::ClientExternalOpen: uuid = %d, name = %s", args=...) at vsnprintf.c:114
#3  0x76f1c778 in jack_format_and_log(int, char const*, char const*, std::__va_list) () from /usr/lib/libjackserver.so.0
#4  0x76f1c8b0 in jack_log () from /usr/lib/libjackserver.so.0
#5  0x76f49c98 in Jack::JackEngine::ClientExternalOpen(char const*, int, unsigned long long, int*, int*, int*, int*) ()
   from /usr/lib/libjackserver.so.0
#6  0x76f75c08 in Jack::JackLockedEngine::ClientExternalOpen(char const*, int, unsigned long long, int*, int*, int*, int*) ()
   from /usr/lib/libjackserver.so.0
#7  0x76f75030 in Jack::JackSocketServerChannel::ClientAdd(Jack::detail::JackChannelTransactionInterface*, Jack::JackClientOpenRequest*, Jack::JackClientOpenResult*) () from /usr/lib/libjackserver.so.0
#8  0x76f6d52c in Jack::JackRequestDecoder::HandleRequest(Jack::detail::JackChannelTransactionInterface*, int) ()
   from /usr/lib/libjackserver.so.0
#9  0x76f6d42c in Jack::JackRequestDecoder::HandleRequest(Jack::detail::JackChannelTransactionInterface*, int) ()
   from /usr/lib/libjackserver.so.0
#10 0x76f758d8 in Jack::JackSocketServerChannel::Execute() () from /usr/lib/libjackserver.so.0
#11 0x76f3b288 in Jack::JackPosixThread::ThreadHandler(void*) () from /usr/lib/libjackserver.so.0
#12 0x76ea6494 in start_thread (arg=0x712233e0) at pthread_create.c:486
#13 0x76b6c578 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

**Comment by falkTX** [comment]
name string looks broken, memory corruption maybe?

does this also happen with simpler example clients?

**Comment by hires** [comment]
I tried a bunch of the example clients built along with the source and they all seem to fail in a similar way.

**Comment by hires** [comment]
Just a quick follow-up... I build version 1.9.12 from source, since the package version in my repo is 1.9.12, and it starts up and runs without error.
