### ISSUE TITLE
Can't run jack_control as root

### ISSUE THREAD

**Issue by kflak** [jackaudio/jack2#581]
Hi, 

I'm trying to set up a udev rule that calls a script on when plugging/unplugging my usb soundcard, but I'm running into issues with dbus. It seems it is not possible to run this script (select_soundcard.sh) as root:
```
#!/bin/bash

case "$1" in 
    "rme")
        device=hw:UCX23815246,0
        nperiods=3
        inchannels=18
        outchannels=18
        period=128
        soundcard=0
        rate=44100
        ;;
    "internal")
        device=hw:PCH,0
        nperiods=2
        inchannels=2
        outchannels=2
        period=512
        soundcard=0
        rate=44100
        ;;
    *)
        notify-send -t 3000 "No soundcard specified"
        soundcard=1
        ;;
esac

if [ $soundcard -eq 0 ]
then
    jack_control stop
    jack_control ds alsa
    jack_control dps device $device
    jack_control dps capture $device
    jack_control dps playback $device
    jack_control dps rate $rate
    jack_control dps nperiods $nperiods
    jack_control dps inchannels $inchannels
    jack_control dps outchannels $outchannels
    jack_control dps period $period
    jack_control dps duplex true
    jack_control dps midi-driver seq
    jack_control start

    wait $!

    jack_control status > /dev/null
    status=$? 
    if [ $status -eq 0 ]
    then
        case $rate in  
            44100) sr="44.1k" ;;
            48000) sr="48k" ;;
            96000) sr="96k" ;;
            *) sr="-" ;;
        esac
        notify-send -t 3000 "$device connected"
        # echo $device $period/$sr > $HOME/.local/share/jackinfo
    else
        notify-send -t 3000 "Error: Jack didn't start"
        # echo "Jack didn't start" > $HOME/.local/share/jackinfo
    fi
fi
```
The output of `sudo select_soundcard.sh rme` is
```
Traceback (most recent call last):
  File "/usr/bin/jack_control", line 400, in <module>
    main()
  File "/usr/bin/jack_control", line 159, in main
    bus = dbus.SessionBus()
  File "/usr/lib/python3.8/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.8/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.8/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
... etc.
```
I tried running `chown root select_soundcard.sh`, I tried moving it to /usr/bin/, I even tried running it as a systemd-service, but always getting the dbus error. Also tried running it as suo

Maybe I'm attacking this the wrong way? My main motivation is to be able to hotplug the soundcard, so if there are better ways of writing a udev rule I am very much open to this! The current rule I'm trying to get to work is 
```
/etc/udev/rules.d/91-rme.rules
---
SUBSYSTEMS=="usb", ATTRS{product}=="Fireface UCX (23815246)", ACTION=="change", RUN+="/home/user/select_soundcard.sh rme"
```
which works fine if I comment out anything jack_control-related in the script.
System: arch linux 5.6.10-rt5-1-rt
Swaywm (wayland)

**Comment by falkTX** [comment]
DBus is not meant to be used as root, try to change this to your own user somehow

**Comment by kflak** [comment]
That's a bit the problem: I've tried 
```
runuser -l user -c "/home/user/bin/select_soundcard.sh rme"
```
but still getting the same errors. Maybe I have to bite the bullet and start using `jackd` instead...?

**Comment by falkTX** [comment]
well, for running stuff as kernel/udev triggers might be a bit tricky to just use a script like that.
you are going to be missing the env vars needed for dbus interaction too.

one possible way could be to trigger a systemd service instead of a bash script.
then on the systemd service file you can specify exactly what you need: user id, needs dbus etc.

**Comment by kflak** [comment]
Aha, that's a bit above my current skills level, but that sounds like an interesting way to go. However, I would like to avoid too much code duplication: currently I have a keybinding in my system to easily switch between the internal and external soundcard, and it would be great to use the same script for both usecases...

**Comment by falkTX** [comment]
you can use the same script, just set up as one-shot systemd service.
something like:
```
[Unit]
Description=usb switch

[Service]
Type=simple
ExecStartPre=/usr/bin/jack_wait -w
ExecStart=-/usr/bin/myscript.sh
Restart=no
User=user1
Group=user1
```

and udev rule like this:
```
ACTION=="add", KERNEL==...., RUN+="/usr/bin/systemctl start myservice"
```

I am using something like that to add specific devices as jack clients, but it is with arguments, and not using dbus.
In any case, if you feel like trying, maybe those will be useful

**Comment by kflak** [comment]
Thanks a lot! Still getting the dbus errors, though, so I suppose I'll give it a go with the jackd-version instead...
