### ISSUE TITLE
1.9.17 fails: UnboundLocalError: local variable 'env_includes' referenced before assignment

### ISSUE THREAD

**Issue by yurivict** [jackaudio/jack2#739]
```
===>  Building for jack2-1.9.17
Waf: Entering directory `/usr/ports/audio/jack2/work/jack2-1.9.17/build'
Traceback (most recent call last):
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Scripting.py", line 159, in waf_entry_point
    run_commands()
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Scripting.py", line 252, in run_commands
    ctx = run_command(cmd_name)
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Scripting.py", line 236, in run_command
    ctx.execute()
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Scripting.py", line 574, in execute
    return execute_method(self)
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Build.py", line 231, in execute
    self.execute_build()
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Build.py", line 244, in execute_build
    self.recurse([self.run_dir])
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Context.py", line 286, in recurse
    user_function(self)
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/wscript", line 782, in build
    bld.recurse('common')
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/waflib/Context.py", line 286, in recurse
    user_function(self)
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/common/wscript", line 381, in build
    create_jack_process_obj(bld, 'netmanager', 'JackNetManager.cpp', serverlib)
  File "/usr/ports/audio/jack2/work/jack2-1.9.17/common/wscript", line 35, in create_jack_process_obj
    process.includes = ['.'] + env_includes + ['jack', '..']
UnboundLocalError: local variable 'env_includes' referenced before assignment
```

OS: FreeBSD 12.2

**Comment by yurivict** [comment]
The ```else``` statement is missing here https://github.com/jackaudio/jack2/blob/develop/common/wscript#L35

With it the error message would have been suggestive.
